### PR TITLE
feat: add the post_thumbnail parameter

### PR DESCRIPTION
**Pull request by razonyang**
Hide the thumbnails if false

### CODE REVIEW

**Comment by FuadEfendi** [comment]
Thank you Razon, it works!
Can you implement this feature for Carousel too?

**Comment by razonyang** [comment]
You're welcome, the carousel be disabled by removing the `featured` parameter from page's front matter.

**Comment by razonyang** [comment]
@FuadEfendi You're welcome, the carousel be disabled by removing the featured parameter from page's front matter.

**Comment by FuadEfendi** [comment]
Yes I know I can completely disable carousel; I'll disable it probably (by removing "featured" from page);

right now I do workaround like this:
`.hb-carousel .carousel-img, .hb-carousel .carousel-img-placeholder {
    height: 94px;
}`

Would be nice to put Carousel in center of screen:
image

Live website:
https://fuadefendi.com/

**Comment by razonyang** [comment]
> Yes I know I can completely disable carousel

Do you mean just remove the image and keep the title and indicators/controls buttons? But it looks a little bit strange. And I didn't have a solution in mind, since the title and other stuff are absolute, fixed height is not a good approach.

Screenshot on mobile device of your site.

image

Perhaps we can change the layout as follows, use pinned posts instead of carousel.

------------------------------
           Carousel
------------------------------
Pinned Posts Up to 3
------------------------------
       Taxonomies
------------------------------
       Recent Posts
------------------------------

**Comment by razonyang** [comment]
@FuadEfendi please feel free to upgrade via `hugo mod get github.com/hbstack/blog@v0.8.1`, should be better.

**Pull request merged**
